
trigger: none

pool:
  name: Kalppool

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: MavenBuild
    displayName: "Maven Build Job"
    steps:
    - checkout: self
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
