stages:
- stage: stageA
  pool:
    name: Kalppool
  displayName: "this is stage A"
  jobs:
  - job: jobA
  - job: jobB
    displayName: "jobB is running on window machine"
    pool:
      vmImage: windows-latest
