trigger:
- main

pool:
  name: Kalppool

stages:
- stage: A
  jobs:
  - job: JobA
    steps:
    - task: PowerShell@1
      inputs:
        scriptType: 'inlineScript'
        inlineScript: |
          # You can write your powershell scripts inline here.
          # You can also pass predefined and custom variables to this scripts using arguments

          Write-Host "Hello World"
      
