trigger: none

parameters:
  - name: PoolName
    displayName: "Choose Pool"
    default: Kalppool
    type: string
    values:
      - Kalppool       # tamaru self-hosted pool
      - macOS-latest   # hosted agent
      - windows-latest # hosted agent

steps:
  - script: echo "Hello, running on ${{ parameters.PoolName }}"
    displayName: "Run on selected pool"
