
trigger: none

pool:
  name: Kalppool

stages:
- stage: CheckoutCode
  jobs:
  - job: Checkoutgitcode
    steps:
    - checkout: self

- stage: Build
  jobs:
  - job:
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
